function calculateFS() {
  // Get input values
  const cohesion = parseFloat(document.getElementById("cohesion").value);
  const area = parseFloat(document.getElementById("area").value);
  const weight = parseFloat(document.getElementById("weight").value);
  const frictionAngle = parseFloat(document.getElementById("frictionAngle").value);
  const slopeAngle = parseFloat(document.getElementById("slopeAngle").value);

  // Check for invalid inputs
  if (isNaN(cohesion) || isNaN(area) || isNaN(weight) || isNaN(frictionAngle) || isNaN(slopeAngle)) {
    alert("Please enter valid numbers for all fields.");
    return;
  }

  // Convert angles to radians
  const phiRadians = (frictionAngle * Math.PI) / 180;
  const thetaRadians = (slopeAngle * Math.PI) / 180;

  // Calculate forces
  const resistingForce = cohesion * area + weight * Math.cos(thetaRadians) * Math.tan(phiRadians);
  const drivingForce = weight * Math.sin(thetaRadians);
  const FS = resistingForce / drivingForce;

  // Display result
  document.getElementById("result").innerText = `Factor of Safety (FS): ${FS.toFixed(2)}`;
}

function generatePDF() {
  // Get input values
  const cohesion = parseFloat(document.getElementById("cohesion").value);
  const area = parseFloat(document.getElementById("area").value);
  const weight = parseFloat(document.getElementById("weight").value);
  const frictionAngle = parseFloat(document.getElementById("frictionAngle").value);
  const slopeAngle = parseFloat(document.getElementById("slopeAngle").value);

  // Convert angles to radians
  const phiRadians = (frictionAngle * Math.PI) / 180;
  const thetaRadians = (slopeAngle * Math.PI) / 180;

  // Calculate forces
  const resistingForce = cohesion * area + weight * Math.cos(thetaRadians) * Math.tan(phiRadians);
  const drivingForce = weight * Math.sin(thetaRadians);
  const FS = resistingForce / drivingForce;

  // Prepare jsPDF
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // Title Page
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Sliding Wedge Calculator Report", 105, 30, null, null, "center");
  doc.setFontSize(12);
  doc.setFont("Helvetica", "normal");
  doc.text("Generated by: Your Company Name", 105, 40, null, null, "center");
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 50, null, null, "center");
  doc.text("------------------------------------------------------------", 10, 60);
  doc.addPage();

  // Input Values Section
  doc.setFontSize(16);
  doc.text("Input Values", 10, 20);
  doc.setFontSize(12);
  doc.text(`Cohesion (c): ${cohesion} kPa`, 10, 30);
  doc.text(`Area (A): ${area} m²`, 10, 40);
  doc.text(`Weight (W): ${weight} kN`, 10, 50);
  doc.text(`Friction Angle (φ): ${frictionAngle}°`, 10, 60);
  doc.text(`Slope Angle (θ): ${slopeAngle}°`, 10, 70);

  // Calculation Steps Section
  doc.setFontSize(16);
  doc.text("Calculation Steps", 10, 90);
  doc.setFontSize(12);
  const steps = [
    `Convert angles to radians:`,
    `   - Friction Angle (φ): ${frictionAngle}° = ${phiRadians.toFixed(3)} radians`,
    `   - Slope Angle (θ): ${slopeAngle}° = ${thetaRadians.toFixed(3)} radians`,
    `Calculate resisting force:`,
    `   - Resisting Force = c × A + W × cos(θ) × tan(φ)`,
    `   - Resisting Force = ${cohesion} × ${area} + ${weight} × cos(${thetaRadians.toFixed(3)}) × tan(${phiRadians.toFixed(3)})`,
    `   - Resisting Force = ${resistingForce.toFixed(2)} kN`,
    `Calculate driving force:`,
    `   - Driving Force = W × sin(θ)`,
    `   - Driving Force = ${weight} × sin(${thetaRadians.toFixed(3)})`,
    `   - Driving Force = ${drivingForce.toFixed(2)} kN`,
    `Calculate Factor of Safety (FS):`,
    `   - FS = Resisting Force / Driving Force`,
    `   - FS = ${resistingForce.toFixed(2)} / ${drivingForce.toFixed(2)}`,
    `   - FS = ${FS.toFixed(2)}`
  ];
  let y = 100;
  steps.forEach((step) => {
    doc.text(step, 10, y);
    y += 10;
    if (y > 270) {
      doc.addPage();
      y = 10;
    }
  });

  // Results Section
  doc.setFontSize(16);
  doc.text("Results", 10, y + 20);
  doc.setFontSize(12);
  doc.text(`Factor of Safety (FS): ${FS.toFixed(2)}`, 10, y + 30);

  // Save PDF
  doc.save("sliding_wedge_report.pdf");
}
